### ISSUE TITLE
erro: page build and deployment fails with "Process completed with exit code 1."

### ISSUE THREAD

**Issue by raianecardoso** [meadapt/meadapt.com#65]
- Criei um novo post para a meadapt.com neste repo em uma branch 
- Ao aceitar o PR e fazer o 'merge' na main, o actuons do GH falhou ao fazer o deply e publicar as alterações, com o erro 'Error: Process completed with exit code 1.'  Segue log completo

`Run mkdocs gh-deploy
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/runner/work/meadapt.com/meadapt.com/site
INFO    -  Documentation built in 0.98 seconds
WARNING -  Version check skipped: No version specified in previous deployment.
INFO    -  Copying '/home/runner/work/meadapt.com/meadapt.com/site' to 'gh-pages' branch and pushing to GitHub.
To https://github.com/meadapt/meadapt.com
 ! [rejected]        gh-pages -> gh-pages (fetch first)
error: failed to push some refs to 'https://github.com/meadapt/meadapt.com'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.2/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 115[7](https://github.com/meadapt/meadapt.com/actions/runs/11871572128/job/33084246119#step:6:8), in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 107[8](https://github.com/meadapt/meadapt.com/actions/runs/11871572128/job/33084246119#step:6:9), in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs/__main__.py", line 318, in gh_deploy_command
    gh_deploy.gh_deploy(
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs/commands/gh_deploy.py", line 12[9](https://github.com/meadapt/meadapt.com/actions/runs/11871572128/job/33084246119#step:6:10), in gh_deploy
    ghp_import.ghp_import(
  File "/opt/hostedtoolcache/Python/3.[10](https://github.com/meadapt/meadapt.com/actions/runs/11871572128/job/33084246119#step:6:11).2/x64/lib/python3.10/site-packages/ghp_import.py", line 285, in ghp_import
    git.check_call('push', opts['remote'], opts['branch'])
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/ghp_import.py", line [11](https://github.com/meadapt/meadapt.com/actions/runs/11871572128/job/33084246119#step:6:12)9, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages']' returned non-zero exit status 1.
Error: Process completed with exit code 1.
`

**Comment by raianecardoso** [comment]
- Após ler esse [issue](https://github.com/actions/upload-pages-artifact/issues/58) com o mesmo erro, a minha primeira teoria era de que os links do Youtube que não estavam funcionando poderiam estar causando esse erro.
- Essa teoria foi testada neste [commit](https://github.com/meadapt/meadapt.com/commit/502d941062ae5627264ffb0d4c499d8390f0ecda). No entanto, o mesmo erro ocorreu. 
-  Uma resposta no stackoverflow sugeriu que poderia ser um erro no próprio action. E, me lembrei que o último PR do @gabrielbdornas alterava alguns actions. Assim, decidi verificar se alguma mudança poderia estar causando o erro. 
- Acontece que esse último PR não alterou o action específico de publicação no site. E, desde a última alteração, há dois meses, eu já havia feito outras publicações. Ou seja, não é um erro no action. 
- Por fim, analisando a estrutura do action e a mensagem de erro, identifiquei que erro ocorria exatamente no último 'job' que é rodar o comando 'mkdocs gh-deploy'. Para essa ação, deduzi que seria necessário conectar com a página, o que a minha rede wifi está bloqueando - see #52.  
- Portanto, a minha segunda teoria era que a minha conexão coma internet estava impedindo o deploy. Mudei da rede wifi para o 5G e fiz uma pequena [alteração](https://github.com/meadapt/meadapt.com/commit/019f8e1a2b3a4c32315e7a0f5b84030be4c9e35b) nesta mesma branch para tentar novo deploy, que foi executado com sucesso. 🎉

**Comment by gabrielbdornas** [comment]
> * Por fim, analisando a estrutura do action e a mensagem de erro, identifiquei que erro ocorria exatamente no último 'job' que é rodar o comando 'mkdocs gh-deploy'. Para essa ação, deduzi que seria necessário conectar com a página, o que a minha rede wifi está bloqueando - see [Site da meadapt não carrega na minha rede wifi #52](https://github.com/meadapt/meadapt.com/issues/52).
> * Portanto, a minha segunda teoria era que a minha conexão coma internet estava impedindo o deploy. Mudei da rede wifi para o 5G e fiz uma pequena [alteração](https://github.com/meadapt/meadapt.com/commit/019f8e1a2b3a4c32315e7a0f5b84030be4c9e35b) nesta mesma branch para tentar novo deploy, que foi executado com sucesso. 🎉

@raianecardoso, que bom que deu certo e parabenizo, principalmente, seu poder de pesquisa.

Comentário sobre a provável solução do problema (já havíamos conversado isso e deixo aqui o registro): Acho que não foi a troca de sua rede para o 5G, pois o actions roda em uma máquina virtual nos servidores do GitHub, não tendo, portando, ligação com sua rede. Mas enfim, funcionou, então vamos que vamos!
